name: deploy

on:
  push:
    branches: [ "main" ]

# 必须添加权限设置，否则 Action 无法将产物发布到 Pages
permissions:
  contents: read
  pages: write
  id-token: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. 环境准备：Rust & Wasm-pack
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      # 2. 执行构建逻辑
      - name: Rust Build (Generate Index)
        run: cargo run --bin gen

      # - name: Wasm Build
        # run: wasm-pack build --target web --release

      # 3. Node.js 环境准备
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22' 

      # 4. 前端打包
      - name: Install & Build Frontend
        run: |
          npm install
          npm run build

      # 5. 上传构建产物 (dist 文件夹)
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    # 设置依赖 build 任务
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
